#-- Choose build environment
virt: lxd               # LXD container
os: linux
dist: focal             # Use Ubuntu 20
language: shell


#-- Choose which branches are built
branches:
  only:
    - master
    - develop

#-- Enable support services
services:
  - docker

#-- Dependencies
install:
  # install any dependencies required
  skip

#-- Define stage order and conditions
stages:
  - name: build
  # - name: deploy
  #   if: branch = master

#-- define jobs and stages
jobs:
  include:
    - stage: build
      script:
        - make docker-build-arm
        - make docker-build-x64
        # - make docker-push
        #   if: branch = master

    # - stage: deploy
    #   script:
    #     - echo "Push to docker hub"
    #     - make docker-build
    #     - make docker-push
    #     - make docker-push-latest
