#-- Choose build environment
os: linux
dist: xenial

language: python
python:
  - "3.6"


#-- Choose which branches are built
branches:
  only:
    - master
    - develop

#-- Enable support services
services:
  - docker




stages:
  - name: build-app
  - name: build-docker
  - name: deploy


#-- Dependencies
install:
  # install any dependencies required
  skip


#-- define jobs and stages
jobs:
  include:
    # Build application
    - stage: build-app
      script: make build
    # Build docker images in parallel
    - stage: build-docker
      script: make docker-build-arm
    -
      script: make docker-build-x64
    # docker push
    - stage: deploy
      script: make docker-push
      if: branch = develop

#-- deploy to docker hub
# deploy:
#   provider: script
#   script: make docker-push
#   on:
#     branch: develop
