#-- Choose build environment
os: linux
dist: xenial
language: python
python:
  - "3.6"


#-- Choose which branches are built
branches:
  only:
    - master
    - develop

#-- Enable support services
services:
  - docker

#-- Dependencies
install:
  # install any dependencies required
  skip

script:
  - make docker-build-arm
  - make docker-build-x64


# deploy:
#   provider: script
#   script: make docker-push
#   on:
#     branch: master
