#-- Choose build environment
# virt: lxd               # LXD container
os: linux
# dist: focal             # Use Ubuntu 20
language: shell


#-- Choose which branches are built
branches:
  only:
    - master
    - develop

#-- Enable support services
services:
  - docker

#-- Dependencies
install:
  # install any dependencies required
  skip

script:
  - make docker-build-arm
  - make docker-build-x64


# deploy:
#   provider: script
#   script: make docker-push
#   on:
#     branch: master
